import MetaApi from 'metaapi.cloud-sdk';

async function test() {
  const token = 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJiZTdmYmFhY2UyOTM0NDk2MjdjNDhlMWM3NDUyNTg5MiIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiYmU3ZmJhYWNlMjkzNDQ5NjI3YzQ4ZTFjNzQ1MjU4OTIiLCJpYXQiOjE3Nzc2MTcxODR9.fWkbHyjteN3-VqnBHZVsUGOMj2p9JoSfMliseOzzP2HrmSLpzp0YbuZfoeVruo64sI1Nut-rF8zyapTa8e3NG-FtJurs0K2lu6Ir9J8JGtGYMDGMs0GHGJhVuGUASg1tyw-y-gsI1WDhlODXdQM5j-Tgf-U9AO0iTgiCJM-AZO6qN4G-4ct6U9_S5ZGfY_OAEa-Rn-kGTUXFlo4fMQLAwWSmr1aeGfzj6H0LZBQ2DXO8tUyuCkmzu3lYXsgeqRVutEqRWUdv29uwYmXw3axnQej55Adx_N10CqCz_9Wf8fja8KyKF_Y23qhVzCFNdYvlmv38UwIWEoSbtdjLazBJfbrV-lAXCFs4m7PnY2LrVKU4SBHUW7CLrsupN4Fl8pa5LzgKidPg4cwuOmKFZWHqnXdOfsCusukV9ou_zMPXxXl_cTGi1dmmeNOPQ5LemtLe_MXkXyLCwHnCFTozdxwfcL0VICq2UPQ70FlmFj-bC3L0gl08Ze9ZaPETNDVtlX_YXe9kpCeyJUxFS6-NPrh0iHDhKhJTenK4qbBTnb8WnFPungfh8at73-y693k86hqTdrvii17aBPtLNFObbelpXqnjMaj0rSc8l-_LRZjRTtZLjDco8XajjmZqbON6iwPBPvhSCSBRXEXhSB4vcR-lSJzEQSHFBDhp3e0ibfcdWJ8';
  const api = new MetaApi(token);
  try {
    await api.metatraderAccountApi.createAccount({
      name: 'MarketSim Test',
      login: '106517277',
      password: 'password',
      server: 'MetaQuotes-Demo',
      platform: 'mt5',
      type: 'cloud'
    });
    console.log('Success');
  } catch (err) {
    console.error(JSON.stringify(err.details || err, null, 2));
  }
}

test();
